# Generated by Django 6.0.2 on 2026-03-13 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditlog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='category',
            field=models.CharField(choices=[('device', 'Device'), ('vendor', 'Vendor'), ('version', 'Version'), ('apikey', 'API Key'), ('gateway', 'Gateway'), ('import', 'Import'), ('export', 'Export'), ('user', 'User')], max_length=20),
        ),
    ]
